# Yleismaalliset asetukset, eli Prometheus noukkii metriikkaa 15 sekunnin välein.
global:
  scrape_interval: 15s

# Määritellään, istä Prometheus kerää metriikkaa.
# Tässä Prometheuksella on kaksi työtä: se kerää metriikkaa itsestään (prometheus:9090) ja sesimerkkisovelluksen API:sta (api:5000).
# API:n metriikkapolku on määritetty olemaan /metrics.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:5000']
    metrics_path: /metrics
